module.exports={
    PRODUCT_COLLECTION:"product",
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    VENDOR_COLLECTION:'vendor',
    CATEGORY_COLLECTION:'categories',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    BANNER_COLLECTION:'banner',
    COUPON_COLLECTION:'coupon'
}